### PR TITLE
Feature: Enhance Analaytics module to fetch Ontology visits, User visits, and the Most visited pages in the month 

### PR DESCRIPTION
**Pull request by syphax-bouazzouni**
### Changes
- Upgrade our code to the latest release of NCBO: https://github.com/ncbo/ncbo_cron/releases/tag/v5.26.0
  - Add an option to not generate the annotator dictionary on each ontology parsing 
  - update ncbo_ontology_archive_old_submissions script
  - update ncbo_ontology_import script, to create contacts if inexistent  

- Update the analytics module to use the new version of the Google Analytics client (starting 2023), this needs a new configuration file 
```ruby
 # Google Analytics GA4 config
  config.analytics_path_to_key_file          = "config/your_analytics_key.json"
  config.analytics_property_id                  = "123456789"
  config.analytics_path_to_ga_data_file = "data/your_ga_data.json"  # will be created if not-existent 
  config.analytics_start_date                    = '2015-01-01' # since when we want to fetch Google Analytics  
```
- Update the Analytics module, to fetch and save, in addition to Ontology visits, now also User visits, and the Most visited pages in the previous month.
- Add a script to import and save Google Analytics UA (2013-2023)

### CODE REVIEW

**Comment by syphax-bouazzouni** [comment]
Hi @mdorf (or @alexskr ), can you provide me information on where I find these JSON files related to the new Google Analytics configuration  (it would be also good if you can add samples)

**Comment by alexskr** [comment]
analytics_path_to_**ua**_data_file file contains exported Google **U**niversal **A**nalytics data. It can be empty if you haven't previously used Google Universal Analytics/old data) data.
analytics_path_to_ga_data_file is a file that gets populated by the process and initially can be empty.
I have created https://github.com/ncbo/ncbo_cron/issues/71 to update documentation on how to generate yaml file containing exported google universal analytics data.

**Comment by syphax-bouazzouni** [comment]
> analytics_path_to_**ua**_data_file file contains exported Google **U**niversal **A**nalytics data. It can be empty if you haven't previously used Google Universal Analytics/old data) data. analytics_path_to_ga_data_file is a file that gets populated by the process and initially can be empty. I have created [ncbo#71](https://github.com/ncbo/ncbo_cron/issues/71) to update documentation on how to generate yaml file containing exported google universal analytics data.

We have used Google Analytics for years so I assume we have Google Universal Analytics data, the question would be where do I find the button "export to JSON"?  I didn't not find any easy solution to do it without doing a script that calls there API.

**Comment by mdorf** [comment]
> > analytics_path_to_**ua**_data_file file contains exported Google **U**niversal **A**nalytics data. It can be empty if you haven't previously used Google Universal Analytics/old data) data. analytics_path_to_ga_data_file is a file that gets populated by the process and initially can be empty. I have created [ncbo#71](https://github.com/ncbo/ncbo_cron/issues/71) to update documentation on how to generate yaml file containing exported google universal analytics data.
> 
> We have used Google Analytics for years so I assume we have Google Universal Analytics data, the question would be where do I find the button "export to JSON"? I didn't not find any easy solution to do it without doing a script that calls there API.

Please see #71

**Pull request merged**
